#!/bin/bash
#
# Scott Burleigh
# February 26, 2012
#

# documentation boilerplate


#python download.py M9OB77Skc < machineMap
scp Remote/* john@sagerlt:/home/john/gitwork/ion-gui/examples/bench-tcp/Remote
scp dotest_remote john@sagerlt:/home/john/gitwork/ion-gui/examples/bench-tcp
ssh john@sagerlt "cd gitwork/ion-gui/examples/bench-tcp; ./cleanup; ./dotest_remote" &
sleep 10
chmod +x ./A/ionstart
chmod +x ./A/ionstop
chmod +x ./Remote/ionstart
chmod +x ./Remote/ionstop

./cleanup
sleep 1
echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD
rm -f ./ion_nodes
RETVAL=0

# Start nodes.
cd A
./ionstart
sleep 10

cd ../A
bpdriver 10000 ipn:2.1 ipn:3.1 -100000 &

# Wait for transmission to finish.
