#!/bin/bash
#
# Scott Burleigh
# February 26, 2012
#

# documentation boilerplate


python download.py muv4_iKKU < machineMap
scp Remote/* john@sagerlt:/home/john/gitwork/ion-gui/examples/bench-tcp/Remote
ssh john@sagerlt "cd gitwork/ion-gui/examples/bench-tcp; ./cleanup; ./dotest_remote" &
sleep 1
chmod +x ./A/ionstart
chmod +x ./A/ionstop
chmod +x ./Remote/ionstart
chmod +x ./Remote/ionstop

./cleanup
sleep 1
echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD
rm -f ./ion_nodes
RETVAL=0

# Start nodes.
cd A
./ionstart


cd ../A
bpcounter ipn:2.1 10000 &

# Wait for transmission to finish.
echo "Waiting for transmission to finish..."
RUNNING=1
TIMER=0
while [ $RUNNING -eq 1 ]
do
	TIMER=$((++TIMER))
	sleep 1
	echo "...receiving..."
	# some ps don't like -p syntax, most do.
	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
	if [ $RETURN_VALUE -eq 0 ]
	then
		echo "...transmission finished."
		RUNNING=0
	fi
	if [ $TIMER -gt 300 ]
	then
		#infinite loop protection
		echo "...5 minutes passed; giving up."
		RUNNING=0
		RETVAL=1
	fi
done

if [ $RETVAL -eq 1 ]
then
	echo "Test did not complete."
	echo "Stopping ION..."
	cd ../2.bench.tcp
	./ionstop &
	cd ../3.bench.tcp
	./ionstop &
	sleep 5
	killm
	echo "...benchmarking terminated."
	exit $RETVAL
fi
