#!/bin/bash

scp Remote/* john@sagerlt:/home/john/gitwork/ion-gui/examples/bench-tcp/Remote
scp start_remote john@sagerlt:/home/john/gitwork/ion-gui/examples/bench-tcp
#ssh john@sagerlt "cd gitwork/ion-gui/examples/bench-tcp; ./cleanup; ./start_remote" &
chmod +x ./A/ionstart
chmod +x ./A/ionstop
chmod +x ./Remote/ionstart
chmod +x ./Remote/ionstop

./cleanup
sleep 1
echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD
rm -f ./ion_nodes
RETVAL=0

# Start nodes.
cd A
./ionstart
echo "Local started"
sleep 15
