#!/bin/bash
#
# Scott Burleigh
# February 26, 2012
#

# documentation boilerplate
source activate
python download.py n2GS8vogs
chmod +x */ionstart
chmod +x */ionstop

CONFIGFILES=" \
./A/config.bprc \
./A/config.ionconfig \
./A/config.ionrc \
./A/config.ionsecrc \
./A/config.ipnrc \
./Remote/config.bprc \
./Remote/config.ionconfig \
./Remote/config.ionrc \
./Remote/config.ionsecrc \
./Remote/config.ipnrc \
"

echo "########################################"
echo
pwd | sed "s/\/.*\///" | xargs echo "NAME: "
echo
echo "PURPOSE: produce simple throughput benchmark results, for direct
	comparison among computing platforms running ION.  All tests are
	performed using the DTNRG-standard TCP convergence-layer protocol
	between neighboring nodes residing on the same computer.  So
	the results exercise BP in a non-loopback configuration, over
	loopback TCP/IP; the results are therefore unaffected by network
	traffic, router performance, or network interface card performance."

echo
echo "CONFIG: 2 node custom:"
echo
for N in $CONFIGFILES
do
	echo "$N:"
	cat $N
	echo "# EOF"
	echo
done


./cleanup
sleep 1
echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD
rm -f ./ion_nodes
RETVAL=0

# Start nodes.
cd A
./ionstart
sleep 1
cd ../Remote
./ionstart

sleep 3
echo ""
echo "Test 1: 10,000 bundles of 1000 bytes each."
cd ../Remote
bpcounter ipn:3.1 10000 &
BPCOUNTER_PID=$!
sleep 1

cd ../A
bpdriver 10000 ipn:2.1 ipn:3.1 -10000 &



# Wait for transmission to finish.
echo "Waiting for transmission to finish..."
RUNNING=1
TIMER=0
while [ $RUNNING -eq 1 ]
do
	TIMER=$((++TIMER))
	sleep 1
	echo "...receiving..."
	# some ps don't like -p syntax, most do.
	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
	if [ $RETURN_VALUE -eq 0 ]
	then
		echo "...transmission finished."
		RUNNING=0
	fi
	if [ $TIMER -gt 300 ]
	then
		#infinite loop protection
		echo "...5 minutes passed; giving up."
		RUNNING=0
		RETVAL=1
	fi
done

./ionstop

cd ../Remote
./ionstop

if [ $RETVAL -eq 1 ]
then
	echo "Test did not complete."
	echo "Stopping ION..."
	cd ../2.bench.tcp
	./ionstop &
	cd ../3.bench.tcp
	./ionstop &
	sleep 5
	killm
	echo "...benchmarking terminated."
	exit $RETVAL
fi
